from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import Network.Commands as cmds
from start_client import client
import Constants.Vulnerabilities as vuln
import time
from Constants import General as constants

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1035, 668)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 600))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(self.groupBox)
        self.logo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(0, 0))
        self.logo.setMaximumSize(QtCore.QSize(16777215, 80))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("imgs/logos/xploit-hub-logo-nobg.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.menu_btns = QtWidgets.QVBoxLayout()
        self.menu_btns.setSpacing(6)
        self.menu_btns.setObjectName("menu_btns")
        self.line_7 = QtWidgets.QFrame(self.groupBox)
        self.line_7.setEnabled(True)
        self.line_7.setStyleSheet("color: rgb(255, 163, 26);")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.menu_btns.addWidget(self.line_7)
        self.scan_page_btn = QtWidgets.QPushButton(self.groupBox)
        self.scan_page_btn.setEnabled(True)
        self.scan_page_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(13)
        self.scan_page_btn.setFont(font)
        self.scan_page_btn.setMouseTracking(False)
        self.scan_page_btn.setTabletTracking(False)
        self.scan_page_btn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.scan_page_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.scan_page_btn.setAcceptDrops(False)
        self.scan_page_btn.setStyleSheet("border-bottom-color: rgb(0, 0, 0);")
        self.scan_page_btn.setCheckable(False)
        self.scan_page_btn.setAutoExclusive(False)
        self.scan_page_btn.setAutoDefault(False)
        self.scan_page_btn.setDefault(False)
        self.scan_page_btn.setFlat(True)
        self.scan_page_btn.setObjectName("scan_page_btn")
        self.menu_btns.addWidget(self.scan_page_btn)
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        self.line_5.setEnabled(True)
        self.line_5.setStyleSheet("color: rgb(255, 163, 26);")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.menu_btns.addWidget(self.line_5)
        self.history_page_btn = QtWidgets.QPushButton(self.groupBox)
        self.history_page_btn.setEnabled(True)
        self.history_page_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(13)
        self.history_page_btn.setFont(font)
        self.history_page_btn.setFlat(True)
        self.history_page_btn.setObjectName("history_page_btn")
        self.menu_btns.addWidget(self.history_page_btn)
        self.line_6 = QtWidgets.QFrame(self.groupBox)
        self.line_6.setEnabled(True)
        self.line_6.setStyleSheet("color: rgb(255, 163, 26);")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.menu_btns.addWidget(self.line_6)
        self.learn_more_page_btn = QtWidgets.QPushButton(self.groupBox)
        self.learn_more_page_btn.setEnabled(True)
        self.learn_more_page_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(13)
        self.learn_more_page_btn.setFont(font)
        self.learn_more_page_btn.setFlat(True)
        self.learn_more_page_btn.setObjectName("learn_more_page_btn")
        self.menu_btns.addWidget(self.learn_more_page_btn)
        self.line_11 = QtWidgets.QFrame(self.groupBox)
        self.line_11.setEnabled(True)
        self.line_11.setStyleSheet("color: rgb(255, 163, 26);")
        self.line_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setObjectName("line_11")
        self.menu_btns.addWidget(self.line_11)
        self.verticalLayout.addLayout(self.menu_btns)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.settings_btn = QtWidgets.QToolButton(self.groupBox)
        self.settings_btn.setEnabled(True)
        self.settings_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.settings_btn.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/resources/settings_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_btn.setIcon(icon)
        self.settings_btn.setIconSize(QtCore.QSize(30, 30))
        self.settings_btn.setAutoRaise(True)
        self.settings_btn.setObjectName("settings_btn")
        self.horizontalLayout_2.addWidget(self.settings_btn)
        self.account_username = QtWidgets.QLabel(self.groupBox)
        self.account_username.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(11)
        self.account_username.setFont(font)
        self.account_username.setObjectName("account_username")
        self.horizontalLayout_2.addWidget(self.account_username)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_12 = QtWidgets.QFrame(self.groupBox)
        self.line_12.setEnabled(True)
        self.line_12.setStyleSheet("color: rgb(255, 163, 26);")
        self.line_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setObjectName("line_12")
        self.verticalLayout.addWidget(self.line_12)
        self.horizontalLayout.addWidget(self.groupBox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(5, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line.setFont(font)
        self.line.setStyleSheet("color: rgb(255, 163, 26);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(850, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome_page = QtWidgets.QWidget()
        self.welcome_page.setObjectName("welcome_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.welcome_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.welcome_txt = QtWidgets.QTextBrowser(self.welcome_page)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        self.welcome_txt.setFont(font)
        self.welcome_txt.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.welcome_txt.setFrameShadow(QtWidgets.QFrame.Plain)
        self.welcome_txt.setLineWidth(0)
        self.welcome_txt.setObjectName("welcome_txt")
        self.verticalLayout_2.addWidget(self.welcome_txt)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.welcome_page)
        self.new_scan_page = QtWidgets.QWidget()
        self.new_scan_page.setObjectName("new_scan_page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.new_scan_page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scan_title = QtWidgets.QLabel(self.new_scan_page)
        self.scan_title.setEnabled(True)
        self.scan_title.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(30)
        self.scan_title.setFont(font)
        self.scan_title.setStyleSheet("")
        self.scan_title.setAlignment(QtCore.Qt.AlignCenter)
        self.scan_title.setObjectName("scan_title")
        self.verticalLayout_8.addWidget(self.scan_title)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem4)
        self.url_txt = QtWidgets.QLabel(self.new_scan_page)
        self.url_txt.setEnabled(True)
        self.url_txt.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(17)
        self.url_txt.setFont(font)
        self.url_txt.setObjectName("url_txt")
        self.verticalLayout_9.addWidget(self.url_txt)
        self.url_input = QtWidgets.QLineEdit(self.new_scan_page)
        self.url_input.setEnabled(True)
        self.url_input.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.url_input.setFont(font)
        self.url_input.setText("")
        self.url_input.setObjectName("url_input")
        self.verticalLayout_9.addWidget(self.url_input)
        spacerItem5 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem5)
        self.scan_result = QtWidgets.QTextBrowser(self.new_scan_page)
        self.scan_result.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_result.sizePolicy().hasHeightForWidth())
        self.scan_result.setSizePolicy(sizePolicy)
        self.scan_result.setMinimumSize(QtCore.QSize(0, 0))
        self.scan_result.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scan_result.setObjectName("textBrowser")
        self.verticalLayout_9.addWidget(self.scan_result)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem6)
        self.line_14 = QtWidgets.QFrame(self.new_scan_page)
        self.line_14.setEnabled(True)
        self.line_14.setStyleSheet("color: rgb(255, 163, 26);")
        self.line_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_14.setLineWidth(2)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_9.addWidget(self.line_14)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.scan_progress_bar = QtWidgets.QProgressBar(self.new_scan_page)
        self.scan_progress_bar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_progress_bar.sizePolicy().hasHeightForWidth())
        self.scan_progress_bar.setSizePolicy(sizePolicy)
        self.scan_progress_bar.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(12)
        self.scan_progress_bar.setFont(font)
        self.scan_progress_bar.setProperty("value", 3)
        self.scan_progress_bar.setTextVisible(False)
        self.scan_progress_bar.setObjectName("progressBar")
        self.horizontalLayout_7.addWidget(self.scan_progress_bar)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem9)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.line_2 = QtWidgets.QFrame(self.new_scan_page)
        self.line_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(5, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("color: rgb(255, 163, 26);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem10 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem10)
        self.vuln_txt = QtWidgets.QLabel(self.new_scan_page)
        self.vuln_txt.setEnabled(True)
        self.vuln_txt.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(17)
        self.vuln_txt.setFont(font)
        self.vuln_txt.setObjectName("vuln_txt")
        self.verticalLayout_10.addWidget(self.vuln_txt)
        self.scrollArea = QtWidgets.QScrollArea(self.new_scan_page)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 404, 485))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.xss_box = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.xss_box.setEnabled(True)
        self.xss_box.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(14)
        self.xss_box.setFont(font)
        self.xss_box.setStyleSheet("")
        self.xss_box.setIconSize(QtCore.QSize(16, 16))
        self.xss_box.setCheckable(True)
        self.xss_box.setChecked(True)
        self.xss_box.setAutoRepeat(False)
        self.xss_box.setAutoExclusive(False)
        self.xss_box.setTristate(False)
        self.xss_box.setObjectName("xss_box")
        self.verticalLayout_11.addWidget(self.xss_box)
        self.sql_box = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.sql_box.setEnabled(True)
        self.sql_box.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(14)
        self.sql_box.setFont(font)
        self.sql_box.setStyleSheet("")
        self.sql_box.setIconSize(QtCore.QSize(16, 16))
        self.sql_box.setCheckable(True)
        self.sql_box.setChecked(True)
        self.sql_box.setAutoRepeat(False)
        self.sql_box.setAutoExclusive(False)
        self.sql_box.setTristate(False)
        self.sql_box.setObjectName("sql_box")
        self.verticalLayout_11.addWidget(self.sql_box)
        self.brute_force_box = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.brute_force_box.setEnabled(True)
        self.brute_force_box.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(14)
        self.brute_force_box.setFont(font)
        self.brute_force_box.setStyleSheet("")
        self.brute_force_box.setIconSize(QtCore.QSize(16, 16))
        self.brute_force_box.setCheckable(True)
        self.brute_force_box.setChecked(True)
        self.brute_force_box.setAutoRepeat(False)
        self.brute_force_box.setAutoExclusive(False)
        self.brute_force_box.setTristate(False)
        self.brute_force_box.setObjectName("brute_force_box")
        self.verticalLayout_11.addWidget(self.brute_force_box)
        self.dos_box = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.dos_box.setEnabled(True)
        self.dos_box.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(14)
        self.dos_box.setFont(font)
        self.dos_box.setStyleSheet("")
        self.dos_box.setIconSize(QtCore.QSize(16, 16))
        self.dos_box.setCheckable(True)
        self.dos_box.setChecked(True)
        self.dos_box.setAutoRepeat(False)
        self.dos_box.setAutoExclusive(False)
        self.dos_box.setTristate(False)
        self.dos_box.setObjectName("dos_box")
        self.verticalLayout_11.addWidget(self.dos_box)
        self.line_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_13.setEnabled(True)
        self.line_13.setStyleSheet("color: rgb(255, 163, 26);")
        self.line_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_13.setLineWidth(2)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_11.addWidget(self.line_13)
        self.select_all_box = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.select_all_box.setEnabled(True)
        self.select_all_box.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(14)
        self.select_all_box.setFont(font)
        self.select_all_box.setStyleSheet("")
        self.select_all_box.setIconSize(QtCore.QSize(16, 16))
        self.select_all_box.setCheckable(True)
        self.select_all_box.setChecked(True)
        self.select_all_box.setAutoRepeat(False)
        self.select_all_box.setAutoExclusive(False)
        self.select_all_box.setTristate(False)
        self.select_all_box.setObjectName("select_all_box")
        self.verticalLayout_11.addWidget(self.select_all_box)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem11)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.start_scan_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.start_scan_btn.setEnabled(True)
        self.start_scan_btn.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(12)
        self.start_scan_btn.setFont(font)
        self.start_scan_btn.setStyleSheet("background-color: rgb(255, 163, 26);")
        self.start_scan_btn.setFlat(False)
        self.start_scan_btn.setObjectName("start_scan_btn")
        self.horizontalLayout_6.addWidget(self.start_scan_btn)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.addWidget(self.scrollArea)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.new_scan_page)
        self.history_page = QtWidgets.QWidget()
        self.history_page.setObjectName("history_page")
        self.stackedWidget.addWidget(self.history_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1035, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # ===ADDED CODE===
        self.account_username.setText(client.get_username())
        self.scan_progress_bar.hide()

        # =Buttons=
        # Page passing
        self.scan_page_btn.clicked.connect(self.load_new_scan_page)
        self.history_page_btn.clicked.connect(self.load_history_page)

        # Start scan
        self.start_scan_btn.clicked.connect(self.send_scan_request)

        # Select all Check box
        self.boxes = {self.xss_box: vuln.XSS, self.sql_box: vuln.SQL_INJECTION,
                      self.brute_force_box: vuln.BRUTE_FORCE, self.dos_box: vuln.DOS_ATTACK}
        self.select_all_box.clicked.connect(self.select_all)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.scan_page_btn.setText(_translate("MainWindow", "New Scan"))
        self.history_page_btn.setText(_translate("MainWindow", "History"))
        self.learn_more_page_btn.setText(_translate("MainWindow", "Lean More"))
        self.settings_btn.setText(_translate("MainWindow", "..."))
        self.account_username.setText(_translate("MainWindow", "-"))
        self.welcome_txt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Copperplate Gothic Bold\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">Welcome</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">To</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">Xploit Hub</span></p></body></html>"))
        self.scan_title.setText(_translate("MainWindow", "New Scan"))
        self.url_txt.setText(_translate("MainWindow", "URL:"))
        self.scan_result.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.vuln_txt.setText(_translate("MainWindow", "vulnerabilities:"))
        self.xss_box.setText(_translate("MainWindow", "xss"))
        self.sql_box.setText(_translate("MainWindow", "SQL Injection"))
        self.brute_force_box.setText(_translate("MainWindow", "Brute Force"))
        self.dos_box.setText(_translate("MainWindow", "DoS"))
        self.select_all_box.setText(_translate("MainWindow", "Select All"))
        self.start_scan_btn.setText(_translate("MainWindow", "Scan"))


# ===ADDED CODE===
    def load_new_scan_page(self):
        self.stackedWidget.setCurrentWidget(self.new_scan_page)

    def load_history_page(self):
        self.stackedWidget.setCurrentWidget(self.history_page)

    # Set all the checkboxes to that of the select all
    def select_all(self):
        state = self.select_all_box.checkState()
        for box in self.boxes.keys():
            box.setCheckState(state)

    def send_scan_request(self):
        self.scan_progress_bar.show()
        self.scan_progress_bar.setValue(3)
        url = self.url_input.text()
        msg = [url]
        vuln_list = []
        for box in self.boxes.keys():
            if box.isChecked():
                vuln_list.append(self.boxes[box])

        msg = msg + vuln_list
        num_of_vuln = len(vuln_list)

        if url != "" and num_of_vuln > 0:
            client.send_data_list(cmds.NEW_SCAN_CMD, msg)
            start = time.time()

            while time.time() - start < constants.RESPONSE_WAIT_TIMEOUT and len(vuln_list) > 0:
                data = client.receive_data()
                if data is not None:
                    # Check if
                    print(data)
                    if data[0] == cmds.NEW_SCAN_CMD and data[1]:
                        _, _, vuln_type, vuln_found, result = data
                        vuln_list.remove(vuln_type)
                        self.scan_progress_bar.setValue(int(round(100 - (100 / num_of_vuln) * len(vuln_list))))
                        self.scan_result.setText(result)
                        break
                    else:
                        _, _, error = data
                        self.scan_progress_bar.setValue(100)
                        self.scan_result.setText(error)
                        break

        self.scan_progress_bar.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
